[build-system]
# A list of packages that are needed to build your package:
requires = ["setuptools"]  # REQUIRED if [build-system] table is used
# The name of the Python object that frontends will use to perform the build:
build-backend = "setuptools.build_meta"  # If not defined, then legacy behavior can happen.


[project]
name = "functional_autoencoders"
version = "1.0.3"  
description = "Functional autoencoder (FAE) and functional variational autoencoder (FVAE)"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = ["machine learning", "deep learning", "autoencoders"]

authors = [
  {name = "Justin Bunker", email = "jb2200@cantab.ac.uk" },
  {name = "Hefin Lambley", email = "hefin.lambley@warwick.ac.uk" },
]

maintainers = [
  {name = "Justin Bunker", email = "jb2200@cantab.ac.uk" },
  {name = "Hefin Lambley", email = "hefin.lambley@warwick.ac.uk" },
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3 :: Only",
]

dynamic = ["dependencies"]

[project.urls]
"Homepage" = "https://github.com/htlambley/functional_autoencoders"
"Bug Reports" = "https://github.com/htlambley/functional_autoencoders/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.poetry.dependencies]
jax = "^0.11.0"
jaxlib = "^0.11.0"
flax = "^0.12.7"
numpy = "^2.5.1"
scipy = "^1.18.0"
h5py = "^3.16.0"
requests = "^2.34.2"
matplotlib = "^3.11.0"
seaborn = "^0.13.2"
dill = "^0.4.1"
ipywidgets = "^8.1.8"
scikit-learn = "^1.9.0"
tqdm = "^4.70.0"
torch = "^2.13.0"
